chatapp-rails/config/routes.rb
Chatapp::Application.routes.draw do
  
  get "chat_room/new"

  devise_for :users, :skip => [:sessions]
  as :user do
    get    'signin'  => 'devise/sessions#new',     :as => :new_user_session
    post   'signin'  => 'devise/sessions#create',  :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  root to: 'pages#login'
  match 'home' => 'pages#home', :as => :home

  delete 'delete_chat_room/:chat_room_id' => 'chat_rooms#destroy', :as => :delete_chat_room
  resource :chat_rooms
  
  get  'invite/:chat_room_id' => 'chat_rooms#invite', :as => :invite
  post 'invite' => 'chat_rooms#add_membership', :as => :post_invite
  get  'chat/:chat_room_id' => 'chat_rooms#chat', :as => :chat
  post 'post_message' => 'chat_rooms#post_message', :as => :post_message
  get  'channels' => 'chat_rooms#channels', :as => :channels
end

chatapp-rails/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can [:invite, :add_membership], ChatRoom, :creator_id => user.id
    can :chat, ChatRoom, :conversations => { :user_id => user.id }
  end
end

chatapp-rails/app/models/chat_message.rb
class ChatMessage
  include Mongoid::Document
  
  field :user_email, type: String
  field :body, type: String
  field :chat_room_id, type: Integer
  field :timestamp, type: DateTime


  def self.get_history(chat_room_id)
    ChatMessage.where(:chat_room_id => chat_room_id)
  end
end

chatapp-rails/app/models/chat_room.rb
class ChatRoom < ActiveRecord::Base
  attr_accessible :creator_id, :name, :channel

  has_many :conversations, :dependent => :destroy
  has_many :users, :through => :conversations

  validates :name, :presence => true
  validates :name, :uniqueness => true

  before_save :generate_channel

  #Class methods
  def self.get_owned_by_user(user)
    ChatRoom.where("creator_id = ?", user.id)
  end

  def self.get_accessible_for_user(user)
    conversations = Conversation.where("user_id = ?", user.id)
    rooms = []
    conversations.each do |conv|
      rooms << conv.chat_room
    end
    rooms - get_owned_by_user(user)
  end

  #instance methods
  def generate_channel
    self.channel = SecureRandom.hex(4)
  end
end

chatapp-rails/app/models/conversation.rb
class Conversation < ActiveRecord::Base
  attr_accessible :chat_room, :user_active, :user

  belongs_to :user
  belongs_to :chat_room

  def self.mark_user_as_active(chat_room_id, user_id)
    conv = Conversation.where("chat_room_id = ? and user_id = ?", chat_room_id, user_id).first
    if !conv.user_active
      conv.user_active = true
      conv.save
    end
  end

  def self.find_active_users(chat_room_id)
    convs = Conversation.where("chat_room_id = ? and user_active = ?", chat_room_id, true)
    users = []
    convs.each do |conv|
      users << User.find(conv.user_id)
    end
    users
  end
end

chatapp-rails/app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :recoverable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation

  #Relations
  has_many :conversations
  has_many :chat_rooms, :through => :conversations
end

chatapp-rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!, :except => [:login, :channels]

  rescue_from CanCan::AccessDenied do |exception|
    render :file => "#{Rails.root}/public/403.html", :formats => [:html], :status => 403, :layout => false
  end
end

chatapp-rails/app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController

  def new
    @chatroom = ChatRoom.new
  end

  def create
    @chatroom = ChatRoom.new(params[:chat_room])
    @chatroom.creator_id = current_user.id

    if @chatroom.save
      conversation = Conversation.create(:chat_room => @chatroom, :user => current_user)
      SocketNotifier.publish_new_channel(@chatroom.channel)
      redirect_to home_path, notice: "Chat Room created successfully."
    else
      render 'new'
    end
  end

  def destroy
    chatroom = ChatRoom.find(params[:chat_room_id])
    chatroom.destroy

    redirect_to home_path, notice: "Chat Room deleted successfully."
  end

  def invite
    @chatroom = ChatRoom.find(params[:chat_room_id])
    authorize! :invite, @chatroom
  end

  def add_membership
    @chatroom = ChatRoom.find(params[:chat_room_id])
    authorize! :add_membership, @chatroom
    
    @user = User.find_by_email(params[:user_email])
    if @user
      conversation = Conversation.create(:chat_room => @chatroom, :user => @user)
      redirect_to home_path, notice: "User invited successfully." and return
    else
      redirect_to invite_path(@chatroom.id), notice: "User not found." and return
    end
  end

  def chat
    @chatroom = ChatRoom.find(params[:chat_room_id])
    authorize! :chat, @chatroom

    Conversation.mark_user_as_active(@chatroom.id, current_user.id)
    @active_users = Conversation.find_active_users(@chatroom.id)
    session[:chat_room_id] = @chatroom.id
    @chathistory = ChatMessage.get_history(@chatroom.id)
  end

  def post_message
    redirect_to home_path unless session[:chat_room_id]

    if request.xhr?
      chatroom = ChatRoom.find(session[:chat_room_id])
      authorize! :chat, chatroom

      message_publisher = MessagePublisher.new
      msg = params[:message]
      message = {:user => current_user.email, :body => msg, :chat_room_id => chatroom.id, :timestamp => DateTime.now.iso8601(0), :channel => chatroom.channel}
      message_publisher.publish_message(message)
      render :json => {:success => "message received"}.to_json
    end
  end

  def channels
    render :json => ChatRoom.all.map(&:channel).to_json
  end

end

chatapp-rails/app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def login
    redirect_to home_path and return if user_signed_in?
  end
  
  def home
    @owned_chatrooms      = ChatRoom.get_owned_by_user(current_user)
    @accessible_chatrooms = ChatRoom.get_accessible_for_user(current_user)
  end

end

chatapp-rails/app/helpers/application_helper.rb
module ApplicationHelper
end

chatapp-rails/app/helpers/chat_room_helper.rb
module ChatRoomHelper
end

chatapp-rails/app/helpers/pages_helper.rb
module PagesHelper
end

chatapp-rails/app/views/chat_rooms/chat.html.erb
<div id="chat-page">
  <div class="row">
    <div class="large-12 columns">
      <div>
        <h2>Let's Chat - You are in <%= @chatroom.name %></h2>
        <input type="hidden" id="channel" value="<%= @chatroom.channel %>">
      </div>
    </div>
  </div>
  <div class="row">
    <div class="large-9 columns">
      <div class="chat-area">
        <% @chathistory.each do |cm| %>
          <p>
            <span class="ts"><%= cm.timestamp %></span>
            <span class="user"><%= cm.user_email %></span>
            <span class="msg"><%= cm.body %></span>
          </p>
        <% end %>
      </div>
    </div>
    <div class="large-3 columns">
      <div class="participants-area">
        <p class="green">Users</p>
        <% @active_users.each do |user| %>
          <p><%= user.email %></p>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="large-9 columns">
      <div class="type-area">
        <textarea id="chat-message"></textarea>
      </div>
    </div>
  </div>
</div>

chatapp-rails/app/views/chat_rooms/invite.html.erb
<div id="invite-page">
  <div class="row">
    <div class="large-12 columns">
      <h2>Invite a user</h2>
    </div>
  </div>
  <div class="row">
    <div class="large-8 columns">
      <%= form_tag(post_invite_path) do %>
        <%= label_tag(:user_email, "Email:") %>
        <%= text_field_tag(:user_email) %>
        <%= hidden_field_tag(:chat_room_id, @chatroom.id) %>
        <%= submit_tag "Invite", :class => "button" %>
      <% end %>
    </div>
  </div>
</div>

chatapp-rails/app/views/chat_rooms/new.html.erb
<div id="create-chat-page">
  <div class="row">
    <div class="large-12 columns">
      <h2>Create a Chat Room</h2>
    </div>
  </div>
  <div class="row">
    <div class="large-8 columns">
      <% if @chatroom && @chatroom.errors.any? %>
        <div class="alert">
          <% @chatroom.errors.full_messages.each do |msg| %>
            <p><%= msg %></p>
          <% end %>
        </div>
      <% end %>
      <%= simple_form_for @chatroom do |f| %>
        <%= f.input  :name %>
        <%= f.button :submit, :class => "button" %>
      <% end %>
    </div>
  </div>
</div>

chatapp-rails/app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :div, :id => "flash_#{name}", :class => "alert-box", :'data-alert' => true do%>
    <span><%=msg %></span>
    <a href="#" class="close">&times;</a>
  <% end %>
<%end%>

chatapp-rails/app/views/layouts/_navbar.html.erb
<div class="contain-to-grid">
  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">ChatApp</a></h1>
      </li>
    </ul>
    <section class="top-bar-section">
      <ul class="right">
        <% if user_signed_in? %>
          <li class="divider hide-for-small"></li>
          <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
        <% end %>
      </ul>
    </section>
  </nav>
</div>

chatapp-rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <title>ChatApp</title>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <script data-main="/assets/application.js" src="/assets/lib/require/require-jquery.js"></script>
    <%= yield :head %>
  </head>
  <body>
    <div class="container">
      <%= render "layouts/navbar" %>
      <div class="row">
        <div class="large-12 column">
          <%= render "layouts/messages" %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

chatapp-rails/app/views/pages/_accessible_rooms.html.erb
<div class="large-12 columns">
  <h3>My Accessible Rooms</h3>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @accessible_chatrooms.each do |aroom| %>
        <tr>
          <td><%= aroom.name %></td>
          <td><%= link_to "Chat", chat_path(aroom.id), :class => "button" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

chatapp-rails/app/views/pages/_created_rooms.html.erb
<div class="large-12 columns">
  <h3>My Created Rooms</h3>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Action</th>
        <th>Invite</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      <% @owned_chatrooms.each do |oroom| %>
        <tr>
          <td><%= oroom.name %></td>
          <td><%= link_to "Chat", chat_path(oroom.id), :class => "button" %></td>
          <td><%= link_to "Invite Users", invite_path(oroom.id), :class => "button green"%></td>
          <td><%= link_to "Delete", delete_chat_room_path(oroom.id), :method => :delete, data: { confirm: 'Are you sure?' }, :class => "button red" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

chatapp-rails/app/views/pages/home.html.erb
<div id="home-page">
  <div class="row">
    <div class="large-12 columns">
      <h2>Welcome <%= current_user.email %></h2>
    </div>
  </div>
  <div class="row">
    <div class="large-12 columns">
      <%= link_to "Create Chat Room", new_chat_rooms_path, :class => "button" %>
    </div>
  </div>
  <div class="row">
    <%= render "created_rooms" %>
  </div>
  <div class="row">
    <%= render "accessible_rooms" %>
  </div>
</div>

chatapp-rails/app/views/pages/login.html.erb
<div id="login-page">
  <div class="row">
    <div class="large-4 columns">
      <%= render "devise/shared/signup" %>
    </div>
    <div class="large-2 columns border-right">
    </div>
    <div class="large-4 columns large-offset-2">
      <%= render "devise/shared/login" %>
    </div>
  </div>
</div>